/**
 * AVIRAGE CULTURAL CODES
 * The 20 Cultural Codes with complete trait profiles
 */

import { CulturalCode } from "./types";

export const CULTURAL_CODES: CulturalCode[] = [
  // ========================================================================
  // CODE 1: SHOKUNIN
  // ========================================================================
  {
    id: "shokunin",
    name: "Shokunin",
    culture: "Japanese",
    essence: "Lifetime dedication to mastering craft with precision, humility, and soul",
    traitProfile: {
      craftsmanship_drive: 95,
      detail_orientation: 90,
      structure_preference: 75,
      pace_preference: 80,
      emotional_stability: 75,
      tradition_orientation: 85,
      sensory_appreciation: 85,
      meaning_orientation: 80,
      social_energy: 35,
      group_size_preference: 30,
      emotional_expressiveness: 30,
      conflict_navigation: 25,
      influence_drive: 35,
      imperfection_tolerance: 40,
      output_orientation: 45,
      novelty_seeking: 40,
      optimism_baseline: 60,
      stability_seeking: 70,
      nature_connection: 65,
      environmental_sensitivity: 60,
      introspection_depth: 70,
    },
    strongestDifferentiators: [
      { trait: "craftsmanship_drive", score: 95 },
      { trait: "detail_orientation", score: 90 },
      { trait: "sensory_appreciation", score: 85 },
      { trait: "tradition_orientation", score: 85 },
      { trait: "pace_preference", score: 80 },
      { trait: "meaning_orientation", score: 80 },
    ],
  },

  // ========================================================================
  // CODE 2: YUGEN
  // ========================================================================
  {
    id: "yugen",
    name: "Yugen",
    culture: "Japanese",
    essence: "Profound, mysterious beauty - finding depth in subtlety and impermanence",
    traitProfile: {
      sensory_appreciation: 90,
      abstract_thinking: 85,
      introspection_depth: 90,
      emotional_stability: 80,
      nature_connection: 85,
      pace_preference: 85,
      present_moment_focus: 85,
      meaning_orientation: 85,
      tradition_orientation: 80,
      social_energy: 25,
      group_size_preference: 20,
      emotional_expressiveness: 30,
      conflict_navigation: 20,
      detail_orientation: 70,
      craftsmanship_drive: 75,
      structure_preference: 45,
      novelty_seeking: 30,
      optimism_baseline: 55,
      stability_seeking: 50,
      influence_drive: 20,
      output_orientation: 25,
      environmental_sensitivity: 75,
    },
    strongestDifferentiators: [
      { trait: "introspection_depth", score: 90 },
      { trait: "sensory_appreciation", score: 90 },
      { trait: "abstract_thinking", score: 85 },
      { trait: "nature_connection", score: 85 },
      { trait: "pace_preference", score: 85 },
      { trait: "present_moment_focus", score: 85 },
      { trait: "meaning_orientation", score: 85 },
    ],
  },

  // ========================================================================
  // CODE 3: KOSELIG
  // ========================================================================
  {
    id: "koselig",
    name: "Koselig",
    culture: "Norwegian/Scandinavian",
    essence: "Warm, intimate, comfortable spaces with close people",
    traitProfile: {
      environmental_sensitivity: 75,
      group_size_preference: 20,
      emotional_expressiveness: 70,
      social_energy: 35,
      nature_connection: 75,
      sensory_appreciation: 85,
      pace_preference: 80,
      emotional_stability: 70,
      introspection_depth: 65,
      tradition_orientation: 60,
      structure_preference: 50,
      conflict_navigation: 30,
      novelty_seeking: 40,
      stability_seeking: 70,
      meaning_orientation: 65,
      optimism_baseline: 60,
      abstract_thinking: 45,
      detail_orientation: 60,
      craftsmanship_drive: 65,
      output_orientation: 35,
      influence_drive: 30,
    },
    strongestDifferentiators: [
      { trait: "sensory_appreciation", score: 85 },
      { trait: "pace_preference", score: 80 },
      { trait: "nature_connection", score: 75 },
      { trait: "environmental_sensitivity", score: 75 },
      { trait: "emotional_expressiveness", score: 70 },
      { trait: "emotional_stability", score: 70 },
    ],
  },

  // ========================================================================
  // CODE 4: ALLEGRIA
  // ========================================================================
  {
    id: "allegria",
    name: "Allegria",
    culture: "Italian",
    essence: "Vibrant social life, communal joy, public square celebration",
    traitProfile: {
      social_energy: 90,
      emotional_expressiveness: 90,
      group_size_preference: 75,
      pace_preference: 75,
      sensory_appreciation: 90,
      craftsmanship_drive: 80,
      emotional_stability: 40,
      structure_preference: 35,
      conflict_navigation: 55,
      tradition_orientation: 70,
      optimism_baseline: 70,
      influence_drive: 60,
      meaning_orientation: 60,
      introspection_depth: 40,
      abstract_thinking: 50,
      detail_orientation: 65,
      output_orientation: 45,
      novelty_seeking: 45,
      stability_seeking: 55,
      nature_connection: 55,
      environmental_sensitivity: 35,
    },
    strongestDifferentiators: [
      { trait: "social_energy", score: 90 },
      { trait: "emotional_expressiveness", score: 90 },
      { trait: "sensory_appreciation", score: 90 },
      { trait: "craftsmanship_drive", score: 80 },
      { trait: "group_size_preference", score: 75 },
      { trait: "pace_preference", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 5: GINGA
  // ========================================================================
  {
    id: "ginga",
    name: "Ginga",
    culture: "Brazilian",
    essence: "Fluid celebration, spontaneous rhythm, joyful movement and optimism",
    traitProfile: {
      optimism_baseline: 95,
      social_energy: 90,
      group_size_preference: 85,
      emotional_expressiveness: 90,
      structure_preference: 25,
      pace_preference: 55,
      sensory_appreciation: 80,
      conflict_navigation: 55,
      environmental_sensitivity: 25,
      novelty_seeking: 60,
      emotional_stability: 50,
      tradition_orientation: 55,
      meaning_orientation: 50,
      influence_drive: 55,
      introspection_depth: 35,
      abstract_thinking: 45,
      detail_orientation: 40,
      craftsmanship_drive: 55,
      output_orientation: 40,
      stability_seeking: 40,
      nature_connection: 60,
    },
    strongestDifferentiators: [
      { trait: "optimism_baseline", score: 95 },
      { trait: "social_energy", score: 90 },
      { trait: "emotional_expressiveness", score: 90 },
      { trait: "group_size_preference", score: 85 },
      { trait: "sensory_appreciation", score: 80 },
    ],
  },

  // ========================================================================
  // CODE 6: NHẸ NHÀNG
  // ========================================================================
  {
    id: "nhe_nhang",
    name: "Nhẹ Nhàng",
    culture: "Vietnamese",
    essence: "Light, gentle, easy living - unhurried presence and soft comfort",
    traitProfile: {
      pace_preference: 95,
      emotional_stability: 70,
      structure_preference: 30,
      social_energy: 45,
      group_size_preference: 35,
      sensory_appreciation: 80,
      tradition_orientation: 70,
      present_moment_focus: 85,
      introspection_depth: 70,
      meaning_orientation: 60,
      conflict_navigation: 40,
      novelty_seeking: 40,
      optimism_baseline: 55,
      emotional_expressiveness: 50,
      craftsmanship_drive: 65,
      detail_orientation: 60,
      output_orientation: 25,
      stability_seeking: 65,
      nature_connection: 60,
      abstract_thinking: 45,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "pace_preference", score: 95 },
      { trait: "present_moment_focus", score: 85 },
      { trait: "sensory_appreciation", score: 80 },
      { trait: "emotional_stability", score: 70 },
      { trait: "tradition_orientation", score: 70 },
      { trait: "introspection_depth", score: 70 },
    ],
  },

  // ========================================================================
  // CODE 7: JOIE DE VIVRE
  // ========================================================================
  {
    id: "joie_de_vivre",
    name: "Joie de Vivre",
    culture: "French",
    essence: "Refined aesthetic pleasure, sophisticated sensory celebration, intellectual joy",
    traitProfile: {
      sensory_appreciation: 95,
      abstract_thinking: 80,
      craftsmanship_drive: 85,
      meaning_orientation: 70,
      pace_preference: 70,
      tradition_orientation: 70,
      influence_drive: 70,
      detail_orientation: 80,
      emotional_expressiveness: 60,
      social_energy: 60,
      group_size_preference: 50,
      optimism_baseline: 65,
      novelty_seeking: 60,
      emotional_stability: 60,
      conflict_navigation: 55,
      introspection_depth: 70,
      structure_preference: 55,
      output_orientation: 50,
      stability_seeking: 55,
      nature_connection: 55,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "sensory_appreciation", score: 95 },
      { trait: "craftsmanship_drive", score: 85 },
      { trait: "abstract_thinking", score: 80 },
      { trait: "detail_orientation", score: 80 },
      { trait: "pace_preference", score: 70 },
    ],
  },

  // ========================================================================
  // CODE 8: FUEGO
  // ========================================================================
  {
    id: "fuego",
    name: "Fuego",
    culture: "Spanish",
    essence: "Passionate fire, intense emotional expression, dramatic authenticity",
    traitProfile: {
      emotional_expressiveness: 95,
      emotional_stability: 30,
      social_energy: 85,
      pace_preference: 70,
      sensory_appreciation: 85,
      conflict_navigation: 60,
      group_size_preference: 70,
      tradition_orientation: 75,
      meaning_orientation: 75,
      introspection_depth: 70,
      novelty_seeking: 50,
      structure_preference: 40,
      optimism_baseline: 60,
      craftsmanship_drive: 70,
      detail_orientation: 55,
      output_orientation: 45,
      stability_seeking: 45,
      nature_connection: 55,
      abstract_thinking: 55,
      environmental_sensitivity: 40,
      influence_drive: 65,
    },
    strongestDifferentiators: [
      { trait: "emotional_expressiveness", score: 95 },
      { trait: "social_energy", score: 85 },
      { trait: "sensory_appreciation", score: 85 },
      { trait: "tradition_orientation", score: 75 },
      { trait: "meaning_orientation", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 9: DAVKA
  // ========================================================================
  {
    id: "davka",
    name: "Davka",
    culture: "Israeli",
    essence: "Defiant boldness, audacious innovation, direct resilience",
    traitProfile: {
      conflict_navigation: 95,
      novelty_seeking: 90,
      influence_drive: 85,
      output_orientation: 85,
      stability_seeking: 25,
      optimism_baseline: 75,
      pace_preference: 40,
      structure_preference: 45,
      social_energy: 70,
      emotional_expressiveness: 70,
      abstract_thinking: 70,
      detail_orientation: 50,
      emotional_stability: 60,
      tradition_orientation: 50,
      meaning_orientation: 70,
      craftsmanship_drive: 55,
      group_size_preference: 60,
      introspection_depth: 50,
      sensory_appreciation: 50,
      nature_connection: 50,
      environmental_sensitivity: 40,
    },
    strongestDifferentiators: [
      { trait: "conflict_navigation", score: 95 },
      { trait: "novelty_seeking", score: 90 },
      { trait: "influence_drive", score: 85 },
      { trait: "output_orientation", score: 85 },
      { trait: "optimism_baseline", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 10: UJAMAA
  // ========================================================================
  {
    id: "ujamaa",
    name: "Ujamaa",
    culture: "African (Swahili)",
    essence: "Familyhood togetherness - communal identity and collective wellbeing",
    traitProfile: {
      social_energy: 90,
      group_size_preference: 85,
      emotional_expressiveness: 90,
      meaning_orientation: 85,
      tradition_orientation: 85,
      influence_drive: 45,
      conflict_navigation: 50,
      optimism_baseline: 70,
      emotional_stability: 55,
      introspection_depth: 60,
      pace_preference: 60,
      structure_preference: 55,
      craftsmanship_drive: 65,
      sensory_appreciation: 75,
      novelty_seeking: 45,
      output_orientation: 45,
      stability_seeking: 60,
      nature_connection: 70,
      detail_orientation: 50,
      abstract_thinking: 55,
      environmental_sensitivity: 50,
    },
    strongestDifferentiators: [
      { trait: "social_energy", score: 90 },
      { trait: "emotional_expressiveness", score: 90 },
      { trait: "group_size_preference", score: 85 },
      { trait: "meaning_orientation", score: 85 },
      { trait: "tradition_orientation", score: 85 },
    ],
  },

  // ========================================================================
  // CODE 11: VIDA
  // ========================================================================
  {
    id: "vida",
    name: "Vida",
    culture: "Costa Rican",
    essence: "Pure life - optimistic gratitude, nature connection, simple joy",
    traitProfile: {
      optimism_baseline: 95,
      nature_connection: 90,
      emotional_stability: 75,
      pace_preference: 75,
      meaning_orientation: 70,
      social_energy: 60,
      emotional_expressiveness: 70,
      group_size_preference: 55,
      structure_preference: 35,
      conflict_navigation: 40,
      tradition_orientation: 55,
      novelty_seeking: 50,
      introspection_depth: 60,
      sensory_appreciation: 70,
      craftsmanship_drive: 50,
      detail_orientation: 45,
      output_orientation: 35,
      stability_seeking: 50,
      influence_drive: 40,
      abstract_thinking: 50,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "optimism_baseline", score: 95 },
      { trait: "nature_connection", score: 90 },
      { trait: "emotional_stability", score: 75 },
      { trait: "pace_preference", score: 75 },
      { trait: "meaning_orientation", score: 70 },
    ],
  },

  // ========================================================================
  // CODE 12: BAUHAUS
  // ========================================================================
  {
    id: "bauhaus",
    name: "Bauhaus",
    culture: "German",
    essence: "Structured excellence - form follows function, systematic precision",
    traitProfile: {
      structure_preference: 95,
      detail_orientation: 90,
      craftsmanship_drive: 85,
      output_orientation: 85,
      stability_seeking: 85,
      conflict_navigation: 75,
      abstract_thinking: 70,
      tradition_orientation: 70,
      emotional_stability: 70,
      pace_preference: 55,
      social_energy: 45,
      emotional_expressiveness: 35,
      group_size_preference: 45,
      meaning_orientation: 65,
      introspection_depth: 60,
      sensory_appreciation: 55,
      novelty_seeking: 50,
      optimism_baseline: 55,
      influence_drive: 65,
      nature_connection: 55,
      environmental_sensitivity: 50,
    },
    strongestDifferentiators: [
      { trait: "structure_preference", score: 95 },
      { trait: "detail_orientation", score: 90 },
      { trait: "craftsmanship_drive", score: 85 },
      { trait: "output_orientation", score: 85 },
      { trait: "stability_seeking", score: 85 },
      { trait: "conflict_navigation", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 13: GEZELLIGHEID
  // ========================================================================
  {
    id: "gezelligheid",
    name: "Gezelligheid",
    culture: "Dutch",
    essence: "Cozy togetherness with honest directness - comfortable intimacy",
    traitProfile: {
      conflict_navigation: 90,
      group_size_preference: 30,
      emotional_expressiveness: 60,
      social_energy: 55,
      stability_seeking: 80,
      structure_preference: 65,
      abstract_thinking: 40,
      sensory_appreciation: 70,
      tradition_orientation: 60,
      emotional_stability: 65,
      pace_preference: 60,
      craftsmanship_drive: 65,
      detail_orientation: 60,
      influence_drive: 55,
      meaning_orientation: 55,
      novelty_seeking: 50,
      optimism_baseline: 60,
      introspection_depth: 50,
      output_orientation: 60,
      nature_connection: 60,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "conflict_navigation", score: 90 },
      { trait: "stability_seeking", score: 80 },
      { trait: "sensory_appreciation", score: 70 },
      { trait: "structure_preference", score: 65 },
    ],
  },

  // ========================================================================
  // CODE 14: SANUK
  // ========================================================================
  {
    id: "sanuk",
    name: "Sanuk",
    culture: "Thai",
    essence: "Joyful fun and ease - smiling acceptance, avoiding difficulty",
    traitProfile: {
      conflict_navigation: 20,
      emotional_stability: 70,
      sensory_appreciation: 85,
      structure_preference: 25,
      pace_preference: 70,
      tradition_orientation: 75,
      optimism_baseline: 75,
      social_energy: 70,
      emotional_expressiveness: 75,
      group_size_preference: 60,
      nature_connection: 70,
      meaning_orientation: 70,
      introspection_depth: 65,
      novelty_seeking: 45,
      craftsmanship_drive: 70,
      detail_orientation: 60,
      output_orientation: 35,
      stability_seeking: 50,
      influence_drive: 30,
      abstract_thinking: 55,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "sensory_appreciation", score: 85 },
      { trait: "optimism_baseline", score: 75 },
      { trait: "emotional_expressiveness", score: 75 },
      { trait: "tradition_orientation", score: 75 },
      { trait: "social_energy", score: 70 },
      { trait: "conflict_navigation", score: 20 }, // LOW as differentiator
    ],
  },

  // ========================================================================
  // CODE 15: SADHANA
  // ========================================================================
  {
    id: "sadhana",
    name: "Sadhana",
    culture: "Indian",
    essence: "Spiritual practice and discipline - sacred purpose through dedicated action",
    traitProfile: {
      meaning_orientation: 95,
      abstract_thinking: 90,
      introspection_depth: 90,
      tradition_orientation: 90,
      sensory_appreciation: 85,
      group_size_preference: 80,
      social_energy: 70,
      emotional_expressiveness: 70,
      nature_connection: 75,
      pace_preference: 60,
      craftsmanship_drive: 75,
      detail_orientation: 70,
      structure_preference: 60,
      novelty_seeking: 45,
      emotional_stability: 60,
      optimism_baseline: 60,
      conflict_navigation: 50,
      influence_drive: 55,
      output_orientation: 50,
      stability_seeking: 60,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "meaning_orientation", score: 95 },
      { trait: "abstract_thinking", score: 90 },
      { trait: "introspection_depth", score: 90 },
      { trait: "tradition_orientation", score: 90 },
      { trait: "sensory_appreciation", score: 85 },
    ],
  },

  // ========================================================================
  // CODE 16: JÄMLIK
  // ========================================================================
  {
    id: "jamlik",
    name: "Jämlik",
    culture: "Swedish",
    essence: "Egalitarian balance - just right moderation, sustainable equality",
    traitProfile: {
      stability_seeking: 90,
      structure_preference: 75,
      nature_connection: 80,
      social_energy: 40,
      group_size_preference: 30,
      emotional_expressiveness: 40,
      conflict_navigation: 35,
      emotional_stability: 75,
      introspection_depth: 70,
      pace_preference: 60,
      tradition_orientation: 65,
      abstract_thinking: 50,
      detail_orientation: 70,
      craftsmanship_drive: 75,
      sensory_appreciation: 70,
      meaning_orientation: 65,
      optimism_baseline: 60,
      novelty_seeking: 55,
      influence_drive: 35,
      output_orientation: 60,
      environmental_sensitivity: 70,
    },
    strongestDifferentiators: [
      { trait: "stability_seeking", score: 90 },
      { trait: "nature_connection", score: 80 },
      { trait: "structure_preference", score: 75 },
      { trait: "emotional_stability", score: 75 },
      { trait: "craftsmanship_drive", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 17: MAJLIS
  // ========================================================================
  {
    id: "majlis",
    name: "Majlis",
    culture: "Arabic",
    essence: "Intimate assembly for musical ecstasy - emotional transcendence through art",
    traitProfile: {
      sensory_appreciation: 95,
      meaning_orientation: 90,
      emotional_expressiveness: 85,
      introspection_depth: 85,
      abstract_thinking: 80,
      craftsmanship_drive: 85,
      tradition_orientation: 85,
      detail_orientation: 80,
      social_energy: 65,
      group_size_preference: 50,
      emotional_stability: 50,
      pace_preference: 65,
      nature_connection: 65,
      structure_preference: 60,
      novelty_seeking: 50,
      optimism_baseline: 60,
      conflict_navigation: 45,
      influence_drive: 55,
      output_orientation: 45,
      stability_seeking: 55,
      environmental_sensitivity: 75,
    },
    strongestDifferentiators: [
      { trait: "sensory_appreciation", score: 95 },
      { trait: "meaning_orientation", score: 90 },
      { trait: "emotional_expressiveness", score: 85 },
      { trait: "introspection_depth", score: 85 },
      { trait: "craftsmanship_drive", score: 85 },
      { trait: "tradition_orientation", score: 85 },
    ],
  },

  // ========================================================================
  // CODE 18: VILLMARK
  // ========================================================================
  {
    id: "villmark",
    name: "Villmark",
    culture: "Norwegian",
    essence: "Wild nature living - solitary wilderness connection, open-air necessity",
    traitProfile: {
      nature_connection: 95,
      social_energy: 30,
      group_size_preference: 25,
      introspection_depth: 80,
      emotional_stability: 75,
      pace_preference: 70,
      environmental_sensitivity: 70,
      sensory_appreciation: 80,
      tradition_orientation: 75,
      meaning_orientation: 75,
      craftsmanship_drive: 65,
      detail_orientation: 65,
      emotional_expressiveness: 35,
      structure_preference: 60,
      conflict_navigation: 30,
      abstract_thinking: 50,
      optimism_baseline: 60,
      novelty_seeking: 50,
      influence_drive: 30,
      output_orientation: 35,
      stability_seeking: 70,
    },
    strongestDifferentiators: [
      { trait: "nature_connection", score: 95 },
      { trait: "introspection_depth", score: 80 },
      { trait: "sensory_appreciation", score: 80 },
      { trait: "emotional_stability", score: 75 },
      { trait: "tradition_orientation", score: 75 },
      { trait: "meaning_orientation", score: 75 },
    ],
  },

  // ========================================================================
  // CODE 19: MERAKI
  // ========================================================================
  {
    id: "meraki",
    name: "Meraki",
    culture: "Greek",
    essence: "Soul in creation - putting your essence and love into your work",
    traitProfile: {
      craftsmanship_drive: 95,
      meaning_orientation: 90,
      detail_orientation: 85,
      sensory_appreciation: 85,
      emotional_expressiveness: 80,
      tradition_orientation: 75,
      pace_preference: 75,
      social_energy: 70,
      introspection_depth: 70,
      emotional_stability: 60,
      structure_preference: 60,
      group_size_preference: 55,
      optimism_baseline: 70,
      nature_connection: 65,
      abstract_thinking: 60,
      conflict_navigation: 50,
      novelty_seeking: 50,
      influence_drive: 55,
      output_orientation: 60,
      stability_seeking: 60,
      environmental_sensitivity: 60,
    },
    strongestDifferentiators: [
      { trait: "craftsmanship_drive", score: 95 },
      { trait: "meaning_orientation", score: 90 },
      { trait: "detail_orientation", score: 85 },
      { trait: "sensory_appreciation", score: 85 },
      { trait: "emotional_expressiveness", score: 80 },
    ],
  },

  // ========================================================================
  // CODE 20: LUJA
  // ========================================================================
  {
    id: "luja",
    name: "Luja",
    culture: "Finnish",
    essence: "Solid strength - stoic perseverance, resilient endurance through hardship",
    traitProfile: {
      emotional_stability: 95,
      nature_connection: 85,
      introspection_depth: 80,
      stability_seeking: 80,
      output_orientation: 75,
      tradition_orientation: 75,
      structure_preference: 70,
      craftsmanship_drive: 70,
      social_energy: 25,
      group_size_preference: 20,
      emotional_expressiveness: 25,
      conflict_navigation: 50,
      pace_preference: 60,
      detail_orientation: 65,
      meaning_orientation: 70,
      novelty_seeking: 40,
      optimism_baseline: 50,
      influence_drive: 35,
      sensory_appreciation: 60,
      abstract_thinking: 50,
      environmental_sensitivity: 40,
    },
    strongestDifferentiators: [
      { trait: "emotional_stability", score: 95 },
      { trait: "nature_connection", score: 85 },
      { trait: "introspection_depth", score: 80 },
      { trait: "stability_seeking", score: 80 },
      { trait: "output_orientation", score: 75 },
      { trait: "tradition_orientation", score: 75 },
    ],
  },
];
