// AVIRAGE CULTURAL CODES DATABASE
// 20 Final Cultural Codes with Complete Trait Profiles

export interface CulturalCode {
  id: number;
  code_name: string;
  full_name: string;
  type: "standalone" | "fusion";
  origin: string;
  description: string;
  core_concepts: string[];
  source_cultures?: string[];
  traits: {
    abstract_thinking: number;
    sensory_appreciation: number;
    pattern_recognition: number;
    detail_orientation: number;
    present_moment_focus: number;
    craftsmanship_drive: number;
    structure_preference: number;
    improvisation_comfort: number;
    pace_preference: number;
    output_orientation: number;
    emotional_stability: number;
    emotional_expressiveness: number;
    environmental_sensitivity: number;
    introspection_depth: number;
    optimism_baseline: number;
    social_energy: number;
    group_size_preference: number;
    conflict_navigation: number;
    influence_drive: number;
    collaborative_preference: number;
    tradition_orientation: number;
    novelty_seeking: number;
    stability_seeking: number;
    meaning_orientation: number;
    nature_connection: number;
  };
}

export const culturalCodes: CulturalCode[] = [
  {
    id: 1,
    code_name: "Khoisan",
    full_name: "San/Khoisan",
    type: "standalone",
    origin: "Southern Africa",
    description: "Hyper-acute environmental perception, radical egalitarianism, immediate-return economy, conflict avoidance, present-moment survival intelligence",
    core_concepts: ["Tracking mastery", "Egalitarian ethics", "Environmental attunement"],
    traits: {
      abstract_thinking: 50,
      sensory_appreciation: 95,
      pattern_recognition: 95,
      detail_orientation: 85,
      present_moment_focus: 95,
      craftsmanship_drive: 50,
      structure_preference: 10,
      improvisation_comfort: 95,
      pace_preference: 30,
      output_orientation: 25,
      emotional_stability: 75,
      emotional_expressiveness: 50,
      environmental_sensitivity: 95,
      introspection_depth: 50,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 10,
      conflict_navigation: 35,
      influence_drive: 10,
      collaborative_preference: 95,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 50,
      meaning_orientation: 85,
      nature_connection: 95
    }
  },
  {
    id: 2,
    code_name: "Káyori",
    full_name: "Yoruba",
    type: "standalone",
    origin: "West Africa",
    description: "Expressive ritual creativity, destiny-aware, communal intellect, Ifá divination logic, oral-intellectual tradition",
    core_concepts: ["Ashe (life force)", "Ori (destiny)", "Ritualized aesthetics"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 50,
      improvisation_comfort: 75,
      pace_preference: 50,
      output_orientation: 75,
      emotional_stability: 50,
      emotional_expressiveness: 75,
      environmental_sensitivity: 50,
      introspection_depth: 75,
      optimism_baseline: 75,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 60,
      influence_drive: 75,
      collaborative_preference: 75,
      tradition_orientation: 75,
      novelty_seeking: 50,
      stability_seeking: 50,
      meaning_orientation: 95,
      nature_connection: 85
    }
  },
  {
    id: 3,
    code_name: "Sahén",
    full_name: "Tuareg",
    type: "standalone",
    origin: "Sahara Desert",
    description: "Introspective poetic identity, desert wisdom, existential longing (Assouf), matrilineal structure, nomadic autonomy",
    core_concepts: ["Assouf (soul yearning)", "Desert navigation", "Poetic expression"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 50,
      improvisation_comfort: 75,
      pace_preference: 30,
      output_orientation: 50,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 75,
      optimism_baseline: 35,
      social_energy: 35,
      group_size_preference: 25,
      conflict_navigation: 60,
      influence_drive: 50,
      collaborative_preference: 75,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 75,
      nature_connection: 95
    }
  },
  {
    id: 4,
    code_name: "Enzuka",
    full_name: "Maasai + Zulu Fusion",
    type: "fusion",
    origin: "East Africa",
    description: "Strength through people, courage as social duty. Warrior discipline, collective honor, structured hierarchy, land-identity fusion",
    core_concepts: ["Ubuntu", "Age-grade warrior system", "Collective honor ethic"],
    source_cultures: ["Maasai", "Zulu"],
    traits: {
      abstract_thinking: 43,
      sensory_appreciation: 75,
      pattern_recognition: 50,
      detail_orientation: 50,
      present_moment_focus: 63,
      craftsmanship_drive: 50,
      structure_preference: 75,
      improvisation_comfort: 43,
      pace_preference: 45,
      output_orientation: 63,
      emotional_stability: 75,
      emotional_expressiveness: 50,
      environmental_sensitivity: 85,
      introspection_depth: 43,
      optimism_baseline: 50,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 85,
      influence_drive: 75,
      collaborative_preference: 75,
      tradition_orientation: 85,
      novelty_seeking: 25,
      stability_seeking: 80,
      meaning_orientation: 85,
      nature_connection: 85
    }
  },
  {
    id: 5,
    code_name: "Siyuané",
    full_name: "Ethiopian + Han Chinese Fusion",
    type: "fusion",
    origin: "Highland Ethiopia + Ancient China",
    description: "Harmony sustained across generations. Long continuity, hierarchical order, disciplined tradition, moral endurance",
    core_concepts: ["Simada (dignity)", "Zhongyong (doctrine of mean)", "Civilizational continuity"],
    source_cultures: ["Ethiopian Highland", "Han Chinese"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 50,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 43,
      craftsmanship_drive: 75,
      structure_preference: 85,
      improvisation_comfort: 25,
      pace_preference: 40,
      output_orientation: 75,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 50,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 68,
      conflict_navigation: 43,
      influence_drive: 50,
      collaborative_preference: 63,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 85,
      meaning_orientation: 85,
      nature_connection: 68
    }
  },
  {
    id: 6,
    code_name: "Jaejin",
    full_name: "Korean",
    type: "standalone",
    origin: "Korea",
    description: "Strength forged under constraint. Compressed emotion (Han), intense loyalty bonds (Jeong), extreme diligence, speed under pressure",
    core_concepts: ["Han (collective emotion)", "Jeong (deep bond)", "Compressed modernity"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 50,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 50,
      pace_preference: 60,
      output_orientation: 75,
      emotional_stability: 50,
      emotional_expressiveness: 45,
      environmental_sensitivity: 50,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 75,
      group_size_preference: 65,
      conflict_navigation: 45,
      influence_drive: 75,
      collaborative_preference: 95,
      tradition_orientation: 75,
      novelty_seeking: 50,
      stability_seeking: 75,
      meaning_orientation: 75,
      nature_connection: 50
    }
  },
  {
    id: 7,
    code_name: "Namséa",
    full_name: "Vietnamese + Thai Fusion",
    type: "fusion",
    origin: "Southeast Asia",
    description: "Grace under movement. Water-based cognition, calm resilience, gentle ease, conflict avoidance mastery",
    core_concepts: ["Nhẹ nhàng (gentle ease)", "Sabai (comfort)", "Flowing adaptability"],
    source_cultures: ["Vietnamese", "Thai"],
    traits: {
      abstract_thinking: 50,
      sensory_appreciation: 75,
      pattern_recognition: 50,
      detail_orientation: 63,
      present_moment_focus: 75,
      craftsmanship_drive: 63,
      structure_preference: 50,
      improvisation_comfort: 75,
      pace_preference: 50,
      output_orientation: 63,
      emotional_stability: 63,
      emotional_expressiveness: 45,
      environmental_sensitivity: 75,
      introspection_depth: 50,
      optimism_baseline: 75,
      social_energy: 75,
      group_size_preference: 50,
      conflict_navigation: 45,
      influence_drive: 43,
      collaborative_preference: 75,
      tradition_orientation: 75,
      novelty_seeking: 38,
      stability_seeking: 63,
      meaning_orientation: 50,
      nature_connection: 75
    }
  },
  {
    id: 8,
    code_name: "Shokunin",
    full_name: "Japanese",
    type: "standalone",
    origin: "Japan",
    description: "Perfectionist craftsmanship, group harmony (Wa), aesthetic discipline, ritualized order, mono no aware (pathos of things)",
    core_concepts: ["Shokunin (craftsman spirit)", "Wa (harmony)", "Wabi-sabi"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 95,
      pattern_recognition: 75,
      detail_orientation: 95,
      present_moment_focus: 75,
      craftsmanship_drive: 95,
      structure_preference: 95,
      improvisation_comfort: 25,
      pace_preference: 65,
      output_orientation: 95,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 50,
      conflict_navigation: 35,
      influence_drive: 35,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 95,
      meaning_orientation: 75,
      nature_connection: 85
    }
  },
  {
    id: 9,
    code_name: "Khoruun",
    full_name: "Mongolian",
    type: "standalone",
    origin: "Mongolian Steppe",
    description: "Freedom sustained by movement. Nomadic mobility intelligence, horse-human symbiosis, decentralized strength, environmental toughness",
    core_concepts: ["Tengri (sky deity)", "Nomadic autonomy", "Steppe resilience"],
    traits: {
      abstract_thinking: 50,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 35,
      present_moment_focus: 75,
      craftsmanship_drive: 50,
      structure_preference: 25,
      improvisation_comfort: 95,
      pace_preference: 50,
      output_orientation: 50,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 50,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 30,
      conflict_navigation: 80,
      influence_drive: 75,
      collaborative_preference: 50,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 50,
      meaning_orientation: 75,
      nature_connection: 95
    }
  },
  {
    id: 10,
    code_name: "Lhumir",
    full_name: "Tibetan",
    type: "standalone",
    origin: "Tibetan Plateau",
    description: "Stillness that includes others. Contemplative consciousness, impermanence worldview, compassion discipline, meditation culture",
    core_concepts: ["Bodhicitta", "Impermanence acceptance", "Monastic discipline"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 50,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 95,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 35,
      pace_preference: 30,
      output_orientation: 25,
      emotional_stability: 95,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 95,
      optimism_baseline: 75,
      social_energy: 50,
      group_size_preference: 50,
      conflict_navigation: 30,
      influence_drive: 25,
      collaborative_preference: 75,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 85
    }
  },
  {
    id: 11,
    code_name: "Yatevar",
    full_name: "Indian Vedic + Nahua/Aztec Fusion",
    type: "fusion",
    origin: "Ancient India + Mesoamerica",
    description: "Order embodied through duty. Law as lived ritual, metaphysical abstraction, cosmic worldview, warrior-philosopher synthesis",
    core_concepts: ["Dharma", "Teotl", "Flower-and-song philosophy"],
    source_cultures: ["Indian Vedic", "Nahua/Aztec"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 85,
      detail_orientation: 75,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 85,
      improvisation_comfort: 38,
      pace_preference: 53,
      output_orientation: 63,
      emotional_stability: 50,
      emotional_expressiveness: 75,
      environmental_sensitivity: 75,
      introspection_depth: 95,
      optimism_baseline: 43,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 68,
      influence_drive: 73,
      collaborative_preference: 75,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 85
    }
  },
  {
    id: 12,
    code_name: "Rénara",
    full_name: "Javanese",
    type: "standalone",
    origin: "Java, Indonesia",
    description: "Order maintained through balance. Refined subtlety (Halus), emotional restraint, power through calm, hierarchical harmony",
    core_concepts: ["Halus (refinement)", "Emotional containment", "Ritualized harmony"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 95,
      improvisation_comfort: 25,
      pace_preference: 30,
      output_orientation: 50,
      emotional_stability: 95,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 50,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 75,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 75,
      nature_connection: 85
    }
  },
  {
    id: 13,
    code_name: "Karayni",
    full_name: "Balinese + Quechua Fusion",
    type: "fusion",
    origin: "Bali + Andean Highlands",
    description: "Sacred balance through reciprocity. Mutual responsibility between humans, spirits, land. Communal ritual labor, aesthetic spirituality",
    core_concepts: ["Tri Hita Karana", "Ayni (reciprocity)", "Collective ceremony"],
    source_cultures: ["Balinese", "Quechua"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 85,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 63,
      craftsmanship_drive: 85,
      structure_preference: 75,
      improvisation_comfort: 50,
      pace_preference: 38,
      output_orientation: 75,
      emotional_stability: 63,
      emotional_expressiveness: 50,
      environmental_sensitivity: 95,
      introspection_depth: 50,
      optimism_baseline: 63,
      social_energy: 85,
      group_size_preference: 85,
      conflict_navigation: 53,
      influence_drive: 50,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 95
    }
  },
  {
    id: 14,
    code_name: "Wóhaka",
    full_name: "Maori + Lakota Fusion",
    type: "fusion",
    origin: "Aotearoa + Great Plains",
    description: "Existence as relationship. All beings as kin through ancestry and spirit. Warrior-spiritual synthesis, land-identity fusion, ritual expression",
    core_concepts: ["Whakapapa", "Mitakuye Oyasin", "Sacred circle"],
    source_cultures: ["Maori", "Lakota"],
    traits: {
      abstract_thinking: 63,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 75,
      craftsmanship_drive: 75,
      structure_preference: 50,
      improvisation_comfort: 75,
      pace_preference: 50,
      output_orientation: 50,
      emotional_stability: 75,
      emotional_expressiveness: 75,
      environmental_sensitivity: 95,
      introspection_depth: 63,
      optimism_baseline: 63,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 75,
      influence_drive: 75,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 95
    }
  },
  {
    id: 15,
    code_name: "Tjukari",
    full_name: "Aboriginal Australian",
    type: "standalone",
    origin: "Australia",
    description: "Land remembers through us. Dreamtime cosmology, Songline navigation, non-linear time, deep time consciousness, ecological intelligence",
    core_concepts: ["Dreamtime", "Songlines", "Land-as-law"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 95,
      pattern_recognition: 95,
      detail_orientation: 75,
      present_moment_focus: 95,
      craftsmanship_drive: 50,
      structure_preference: 25,
      improvisation_comfort: 75,
      pace_preference: 30,
      output_orientation: 25,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 25,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 95
    }
  },
  {
    id: 16,
    code_name: "Kinmora",
    full_name: "Maya",
    type: "standalone",
    origin: "Mesoamerica",
    description: "Mastery of cycles. Mathematical cosmology, cyclical time consciousness, astronomical precision, ritual calendrics, sacred kingship",
    core_concepts: ["K'in (time/sun)", "Cyclical cosmology", "Sacred precision"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 95,
      present_moment_focus: 35,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 25,
      pace_preference: 30,
      output_orientation: 50,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 75,
      optimism_baseline: 50,
      social_energy: 50,
      group_size_preference: 50,
      conflict_navigation: 50,
      influence_drive: 50,
      collaborative_preference: 75,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 95
    }
  },
  {
    id: 17,
    code_name: "Siljoa",
    full_name: "Inuit + Sami Fusion",
    type: "fusion",
    origin: "Circumpolar Arctic",
    description: "Living in dialogue with climate and place. Environment as thinking partner. Arctic survival intelligence, small-group cooperation, environmental attunement",
    core_concepts: ["Sila (weather intelligence)", "Joik (vocal land-memory)", "Ayuqniq (acceptance)"],
    source_cultures: ["Inuit", "Sami"],
    traits: {
      abstract_thinking: 50,
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 75,
      present_moment_focus: 75,
      craftsmanship_drive: 75,
      structure_preference: 25,
      improvisation_comfort: 85,
      pace_preference: 30,
      output_orientation: 50,
      emotional_stability: 85,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 50,
      optimism_baseline: 50,
      social_energy: 30,
      group_size_preference: 18,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 85,
      tradition_orientation: 75,
      novelty_seeking: 18,
      stability_seeking: 85,
      meaning_orientation: 80,
      nature_connection: 95
    }
  },
  {
    id: 18,
    code_name: "Skénari",
    full_name: "Haudenosaunee",
    type: "standalone",
    origin: "Eastern Woodlands, North America",
    description: "Responsibility to the unborn. Seventh Generation principle, consensus governance, future-oriented ethics, confederacy structure, peace-centered power",
    core_concepts: ["Seventh Generation", "Great Law", "Consensus democracy"],
    traits: {
      abstract_thinking: 75,
      sensory_appreciation: 50,
      pattern_recognition: 75,
      detail_orientation: 50,
      present_moment_focus: 35,
      craftsmanship_drive: 50,
      structure_preference: 95,
      improvisation_comfort: 25,
      pace_preference: 30,
      output_orientation: 50,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 75,
      optimism_baseline: 75,
      social_energy: 50,
      group_size_preference: 85,
      conflict_navigation: 65,
      influence_drive: 50,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 75
    }
  },
  {
    id: 19,
    code_name: "Ashkara",
    full_name: "Persian/Zoroastrian",
    type: "standalone",
    origin: "Ancient Persia",
    description: "Truth enacted, not believed. Moral choice as sacred action. Ethical dualism, fire symbolism, paradise-garden ideal, good thoughts/words/deeds",
    core_concepts: ["Asha (truth/order)", "Ethical dualism", "Fire purity"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 25,
      pace_preference: 50,
      output_orientation: 75,
      emotional_stability: 75,
      emotional_expressiveness: 50,
      environmental_sensitivity: 50,
      introspection_depth: 95,
      optimism_baseline: 75,
      social_energy: 50,
      group_size_preference: 50,
      conflict_navigation: 60,
      influence_drive: 75,
      collaborative_preference: 50,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 85
    }
  },
  {
    id: 20,
    code_name: "Aléthir",
    full_name: "Ancient Greek",
    type: "standalone",
    origin: "Ancient Greece",
    description: "To live by seeking what is real. Truth emerges through inquiry and dialogue. Rational inquiry, logos-centered thinking, civic debate, philosophical pluralism",
    core_concepts: ["Arete (excellence)", "Logos (reason)", "Aletheia (truth)"],
    traits: {
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 75,
      present_moment_focus: 50,
      craftsmanship_drive: 75,
      structure_preference: 50,
      improvisation_comfort: 50,
      pace_preference: 50,
      output_orientation: 75,
      emotional_stability: 50,
      emotional_expressiveness: 75,
      environmental_sensitivity: 50,
      introspection_depth: 95,
      optimism_baseline: 50,
      social_energy: 75,
      group_size_preference: 50,
      conflict_navigation: 70,
      influence_drive: 75,
      collaborative_preference: 50,
      tradition_orientation: 75,
      novelty_seeking: 75,
      stability_seeking: 50,
      meaning_orientation: 95,
      nature_connection: 85
    }
  }
];

// Helper to get code by name
export function getCodeByName(codeName: string): CulturalCode | undefined {
  return culturalCodes.find(code => code.code_name === codeName);
}

// Helper to get all code names
export function getAllCodeNames(): string[] {
  return culturalCodes.map(code => code.code_name);
}
