/**
 * IDENTITY CODES (ENGINE CANONICAL DATA)
 *
 * RULES (LOCKED):
 * - SINGLE SOURCE OF TRUTH for identity vectors + trait targets
 * - Cultural data = lineage / scientific grounding ONLY
 * - User-facing identity = MYTHIC ARCHETYPES
 * - No simplification, no moral framing, no loss of precision
 *
 * Pipeline:
 * Behavioral data → Cultural research → Abstract vectors → Mythic identity
 */

import { CulturalCode, TraitScores } from "./types";

/* =========================================================
   BASELINE + UTIL
========================================================= */

const BASELINE = 50;

function t(partial: Partial<TraitScores>): TraitScores {
  return {
    abstract_thinking: BASELINE,
    sensory_appreciation: BASELINE,
    pattern_recognition: BASELINE,
    detail_orientation: BASELINE,
    present_moment_focus: BASELINE,

    craftsmanship_drive: BASELINE,
    structure_preference: BASELINE,
    improvisation_comfort: BASELINE,
    pace_preference: BASELINE,
    output_orientation: BASELINE,

    emotional_stability: BASELINE,
    emotional_expressiveness: BASELINE,
    environmental_sensitivity: BASELINE,
    introspection_depth: BASELINE,
    optimism_baseline: BASELINE,

    social_energy: BASELINE,
    group_size_preference: BASELINE,
    conflict_navigation: BASELINE,
    influence_drive: BASELINE,
    collaborative_preference: BASELINE,

    tradition_orientation: BASELINE,
    novelty_seeking: BASELINE,
    stability_seeking: BASELINE,
    meaning_orientation: BASELINE,

    nature_connection: BASELINE,

    ...partial,
  };
}

/* =========================================================
   IDENTITY CODE DEFINITIONS (20)
========================================================= */

export const CULTURAL_CODES: CulturalCode[] = [
  {
    id: 1,
    code_name: "khoisan",
    archetype_name: "Earthlistener",
    archetype_essence: "Presence • attunement • environmental intelligence",
    archetype_symbol: "spiral-stone",
    cultural_lineage: "Southern Africa",
    description:
      "Deeply grounded, perceptive, and present. Strong connection to land, rhythm, and subtle pattern awareness.",
    core_concepts: ["presence", "nature", "community", "adaptation"],
    traits: t({
      sensory_appreciation: 95,
      pattern_recognition: 95,
      detail_orientation: 85,
      present_moment_focus: 95,
      structure_preference: 10,
      improvisation_comfort: 95,
      pace_preference: 30,
      output_orientation: 25,
      emotional_stability: 75,
      environmental_sensitivity: 95,
      social_energy: 50,
      group_size_preference: 10,
      conflict_navigation: 35,
      influence_drive: 10,
      collaborative_preference: 95,
      tradition_orientation: 75,
      novelty_seeking: 25,
      meaning_orientation: 85,
      nature_connection: 95,
    }),
  },

  {
    id: 2,
    code_name: "kayori",
    archetype_name: "Fireweaver",
    archetype_essence: "Expression • emotional transmission • collective rhythm",
    archetype_symbol: "ember-drum",
    cultural_lineage: "West Africa",
    description:
      "Expressive, communal, and emotionally rich. Values rhythm, storytelling, and shared meaning.",
    core_concepts: ["expression", "community", "emotion", "connection"],
    traits: t({
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      craftsmanship_drive: 75,
      output_orientation: 75,
      emotional_expressiveness: 75,
      introspection_depth: 75,
      optimism_baseline: 75,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 60,
      influence_drive: 75,
      collaborative_preference: 75,
      improvisation_comfort: 75,
      tradition_orientation: 75,
      meaning_orientation: 95,
      nature_connection: 85,
    }),
  },

  {
    id: 3,
    code_name: "sahen",
    archetype_name: "HorizonWalker",
    archetype_essence: "Endurance • solitude • internal strength",
    archetype_symbol: "distant-sun",
    cultural_lineage: "Nomadic desert ecologies",
    description:
      "Quietly resilient, inwardly strong, and independent. Comfortable with solitude and long horizons.",
    core_concepts: ["endurance", "autonomy", "introspection", "movement"],
    traits: t({
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      craftsmanship_drive: 75,
      improvisation_comfort: 75,
      pace_preference: 30,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 75,
      optimism_baseline: 35,
      social_energy: 35,
      group_size_preference: 25,
      conflict_navigation: 60,
      collaborative_preference: 75,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 75,
      nature_connection: 95,
    }),
  },

  {
    id: 4,
    code_name: "enzuka",
    archetype_name: "Shieldbearer",
    archetype_essence: "Protective leadership • order • responsibility",
    archetype_symbol: "iron-circle",
    cultural_lineage: "East & Southern Africa",
    description:
      "Grounded leadership through strength, clarity, and protection of the group.",
    core_concepts: ["strength", "order", "responsibility", "leadership"],
    traits: t({
      abstract_thinking: 43,
      sensory_appreciation: 75,
      present_moment_focus: 63,
      structure_preference: 75,
      improvisation_comfort: 43,
      pace_preference: 45,
      output_orientation: 63,
      emotional_stability: 75,
      environmental_sensitivity: 85,
      introspection_depth: 43,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 85,
      influence_drive: 75,
      collaborative_preference: 75,
      tradition_orientation: 85,
      novelty_seeking: 25,
      stability_seeking: 80,
      meaning_orientation: 85,
      nature_connection: 85,
    }),
  },

  {
    id: 5,
    code_name: "siyuane",
    archetype_name: "Kitsune",
    archetype_essence: "Precision • mastery • quiet excellence",
    archetype_symbol: "folded-blade",
    cultural_lineage: "East Africa & East Asia",
    description:
      "Disciplined, precise, and quietly driven. Values mastery, structure, and long-term progress.",
    core_concepts: ["discipline", "mastery", "order", "craft"],
    traits: t({
      abstract_thinking: 75,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 43,
      craftsmanship_drive: 75,
      structure_preference: 85,
      improvisation_comfort: 25,
      pace_preference: 40,
      output_orientation: 75,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      introspection_depth: 75,
      group_size_preference: 68,
      conflict_navigation: 43,
      collaborative_preference: 63,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 85,
      meaning_orientation: 85,
      nature_connection: 68,
    }),
  },

  {
    id: 6,
    code_name: "jaejin",
    archetype_name: "Harmonist",
    archetype_essence: "Order • respect • social equilibrium",
    archetype_symbol: "balanced-knot",
    cultural_lineage: "Korea",
    description:
      "Respectful, structured, and socially attuned. Balances hierarchy with care for harmony.",
    core_concepts: ["respect", "structure", "harmony", "duty"],
    traits: t({
      abstract_thinking: 75,
      pattern_recognition: 75,
      detail_orientation: 75,
      craftsmanship_drive: 75,
      structure_preference: 75,
      pace_preference: 60,
      output_orientation: 75,
      emotional_expressiveness: 45,
      introspection_depth: 75,
      social_energy: 75,
      group_size_preference: 65,
      conflict_navigation: 30,
      influence_drive: 75,
      collaborative_preference: 75,
      tradition_orientation: 75,
      stability_seeking: 75,
      meaning_orientation: 75,
    }),
  },

  {
    id: 7,
    code_name: "namsea",
    archetype_name: "Flowbinder",
    archetype_essence: "Adaptation • relational balance • fluid intelligence",
    archetype_symbol: "tidal-ring",
    cultural_lineage: "Southeast Asia",
    description:
      "Fluid, adaptable, and relational. Moves with change rather than against it.",
    core_concepts: ["flow", "adaptation", "balance", "relationship"],
    traits: t({
      abstract_thinking: 63,
      sensory_appreciation: 75,
      pattern_recognition: 63,
      detail_orientation: 60,
      present_moment_focus: 75,
      craftsmanship_drive: 63,
      improvisation_comfort: 80,
      pace_preference: 45,
      output_orientation: 63,
      emotional_stability: 60,
      emotional_expressiveness: 65,
      environmental_sensitivity: 75,
      introspection_depth: 63,
      optimism_baseline: 63,
      social_energy: 60,
      group_size_preference: 75,
      conflict_navigation: 35,
      influence_drive: 50,
      collaborative_preference: 80,
      tradition_orientation: 75,
      novelty_seeking: 55,
      stability_seeking: 55,
      meaning_orientation: 75,
      nature_connection: 75,
    }),
  },

  {
    id: 8,
    code_name: "shokunin",
    archetype_name: "BladeSmith",
    archetype_essence: "Craft devotion • repetition • exactness",
    archetype_symbol: "anvil-mark",
    cultural_lineage: "Japan",
    description:
      "Devotion to craft, quiet excellence, and precision through repetition.",
    core_concepts: ["craft", "discipline", "precision", "mastery"],
    traits: t({
      abstract_thinking: 75,
      pattern_recognition: 95,
      detail_orientation: 95,
      present_moment_focus: 75,
      craftsmanship_drive: 90,
      structure_preference: 80,
      improvisation_comfort: 25,
      pace_preference: 40,
      output_orientation: 75,
      emotional_stability: 75,
      emotional_expressiveness: 30,
      introspection_depth: 75,
      social_energy: 35,
      group_size_preference: 25,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 50,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 65,
      nature_connection: 75,
    }),
  },

  {
    id: 9,
    code_name: "khoruun",
    archetype_name: "SkyRider",
    archetype_essence: "Freedom • resilience • wide-horizon thinking",
    archetype_symbol: "wind-horse",
    cultural_lineage: "Mongolia",
    description:
      "Independent, resilient, and rooted in vast open environments.",
    core_concepts: ["freedom", "self-reliance", "nature", "endurance"],
    traits: t({
      abstract_thinking: 43,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 60,
      present_moment_focus: 75,
      craftsmanship_drive: 60,
      structure_preference: 43,
      improvisation_comfort: 75,
      pace_preference: 35,
      emotional_stability: 70,
      emotional_expressiveness: 43,
      environmental_sensitivity: 85,
      introspection_depth: 63,
      social_energy: 35,
      group_size_preference: 30,
      conflict_navigation: 60,
      influence_drive: 50,
      collaborative_preference: 60,
      tradition_orientation: 75,
      novelty_seeking: 60,
      stability_seeking: 50,
      meaning_orientation: 63,
      nature_connection: 80,
    }),
  },

  {
    id: 10,
    code_name: "lhumir",
    archetype_name: "StillMind",
    archetype_essence: "Inner clarity • contemplation • disciplined calm",
    archetype_symbol: "silent-flame",
    cultural_lineage: "Tibet",
    description:
      "Calm, contemplative, and meaning-oriented. Values inner clarity over outward noise.",
    core_concepts: ["contemplation", "meaning", "calm", "discipline"],
    traits: t({
      abstract_thinking: 95,
      pattern_recognition: 75,
      detail_orientation: 75,
      present_moment_focus: 75,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 25,
      pace_preference: 30,
      output_orientation: 43,
      emotional_stability: 80,
      emotional_expressiveness: 35,
      environmental_sensitivity: 75,
      introspection_depth: 85,
      optimism_baseline: 65,
      social_energy: 30,
      group_size_preference: 25,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 63,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 85,
      nature_connection: 85,
    }),
  },

  {
    id: 11,
    code_name: "sanskara",
    archetype_name: "CycleKeeper",
    archetype_essence: "Ritual • layered meaning • cosmic order",
    archetype_symbol: "turning-wheel",
    cultural_lineage: "South Asia",
    description:
      "Layered, philosophical, and devoted to ritual precision.",
    core_concepts: ["ritual", "cycles", "devotion", "order"],
    traits: t({
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 75,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 43,
      output_orientation: 75,
      emotional_stability: 60,
      emotional_expressiveness: 75,
      environmental_sensitivity: 63,
      introspection_depth: 95,
      optimism_baseline: 60,
      social_energy: 60,
      group_size_preference: 75,
      conflict_navigation: 43,
      influence_drive: 63,
      collaborative_preference: 63,
      tradition_orientation: 95,
      novelty_seeking: 43,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 75,
    }),
  },

  {
    id: 12,
    code_name: "tahiri",
    archetype_name: "HeartBearer",
    archetype_essence: "Honor • hospitality • expressive warmth",
    archetype_symbol: "open-palm",
    cultural_lineage: "Middle East & North Africa",
    description:
      "Passionate, expressive, and grounded in shared values.",
    core_concepts: ["honor", "hospitality", "expression", "kinship"],
    traits: t({
      abstract_thinking: 75,
      sensory_appreciation: 75,
      pattern_recognition: 68,
      detail_orientation: 60,
      present_moment_focus: 63,
      craftsmanship_drive: 68,
      structure_preference: 60,
      improvisation_comfort: 60,
      pace_preference: 50,
      output_orientation: 63,
      emotional_stability: 60,
      emotional_expressiveness: 75,
      environmental_sensitivity: 68,
      introspection_depth: 68,
      optimism_baseline: 63,
      social_energy: 75,
      group_size_preference: 75,
      conflict_navigation: 60,
      influence_drive: 68,
      collaborative_preference: 68,
      tradition_orientation: 85,
      novelty_seeking: 43,
      stability_seeking: 68,
      meaning_orientation: 85,
      nature_connection: 75,
    }),
  },

  {
    id: 13,
    code_name: "athenos",
    archetype_name: "MuseBearer",
    archetype_essence: "Beauty • passion • expressive vitality",
    archetype_symbol: "laurel-flame",
    cultural_lineage: "Mediterranean",
    description:
      "Passionate, social, and deeply appreciative of beauty and expression.",
    core_concepts: ["beauty", "passion", "community", "expression"],
    traits: t({
      abstract_thinking: 75,
      sensory_appreciation: 85,
      pattern_recognition: 68,
      detail_orientation: 60,
      present_moment_focus: 75,
      craftsmanship_drive: 75,
      structure_preference: 43,
      improvisation_comfort: 75,
      pace_preference: 43,
      output_orientation: 68,
      emotional_expressiveness: 85,
      environmental_sensitivity: 68,
      introspection_depth: 68,
      optimism_baseline: 75,
      social_energy: 85,
      group_size_preference: 75,
      conflict_navigation: 60,
      influence_drive: 68,
      collaborative_preference: 75,
      tradition_orientation: 68,
      novelty_seeking: 60,
      stability_seeking: 55,
      meaning_orientation: 75,
      nature_connection: 68,
    }),
  },

  {
    id: 14,
    code_name: "udumai",
    archetype_name: "AncestorRoot",
    archetype_essence: "Collective memory • environmental unity",
    archetype_symbol: "woven-root",
    cultural_lineage: "South Pacific",
    description:
      "Deeply interconnected, communal, and environment-focused.",
    core_concepts: ["collective", "ancestors", "environment", "strength"],
    traits: t({
      abstract_thinking: 63,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 60,
      present_moment_focus: 75,
      craftsmanship_drive: 63,
      structure_preference: 63,
      pace_preference: 35,
      emotional_stability: 75,
      emotional_expressiveness: 75,
      environmental_sensitivity: 95,
      introspection_depth: 63,
      optimism_baseline: 63,
      social_energy: 75,
      group_size_preference: 85,
      conflict_navigation: 75,
      influence_drive: 75,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 95,
    }),
  },

  {
    id: 15,
    code_name: "tjukari",
    archetype_name: "SonglineKeeper",
    archetype_essence: "Deep time • land-memory • continuity",
    archetype_symbol: "echo-path",
    cultural_lineage: "Australia",
    description:
      "Deep time consciousness, songline navigation, and ecological intelligence.",
    core_concepts: ["continuity", "land-law", "memory", "navigation"],
    traits: t({
      abstract_thinking: 95,
      sensory_appreciation: 95,
      pattern_recognition: 95,
      detail_orientation: 75,
      present_moment_focus: 95,
      structure_preference: 25,
      improvisation_comfort: 75,
      pace_preference: 30,
      output_orientation: 25,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      introspection_depth: 75,
      social_energy: 50,
      group_size_preference: 25,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 95,
    }),
  },

  {
    id: 16,
    code_name: "kinmora",
    archetype_name: "TimeArchitect",
    archetype_essence: "Cycles • precision • cosmic structure",
    archetype_symbol: "celestial-grid",
    cultural_lineage: "Mesoamerica",
    description:
      "Mathematical cosmology and cyclical time consciousness.",
    core_concepts: ["cycles", "time", "precision", "cosmology"],
    traits: t({
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 95,
      present_moment_focus: 35,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 25,
      pace_preference: 30,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 75,
      group_size_preference: 50,
      conflict_navigation: 50,
      collaborative_preference: 75,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 95,
    }),
  },

  {
    id: 17,
    code_name: "siljoa",
    archetype_name: "FrostSentinel",
    archetype_essence: "Climate attunement • resilience • cooperation",
    archetype_symbol: "ice-mark",
    cultural_lineage: "Circumpolar Arctic",
    description:
      "Living in dialogue with climate and place.",
    core_concepts: ["climate", "resilience", "cooperation", "attunement"],
    traits: t({
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 75,
      present_moment_focus: 75,
      craftsmanship_drive: 75,
      structure_preference: 25,
      improvisation_comfort: 85,
      pace_preference: 30,
      emotional_stability: 85,
      emotional_expressiveness: 40,
      environmental_sensitivity: 95,
      social_energy: 30,
      group_size_preference: 18,
      conflict_navigation: 35,
      influence_drive: 25,
      collaborative_preference: 85,
      tradition_orientation: 75,
      novelty_seeking: 18,
      stability_seeking: 85,
      meaning_orientation: 80,
      nature_connection: 95,
    }),
  },

  {
    id: 18,
    code_name: "skenari",
    archetype_name: "FutureGuardian",
    archetype_essence: "Long-horizon ethics • collective responsibility",
    archetype_symbol: "seven-rings",
    cultural_lineage: "Eastern Woodlands, North America",
    description:
      "Responsibility to future generations through consensus governance.",
    core_concepts: ["future", "consensus", "peace", "responsibility"],
    traits: t({
      abstract_thinking: 75,
      pattern_recognition: 75,
      present_moment_focus: 35,
      structure_preference: 95,
      improvisation_comfort: 25,
      pace_preference: 30,
      emotional_stability: 75,
      emotional_expressiveness: 40,
      environmental_sensitivity: 75,
      introspection_depth: 75,
      optimism_baseline: 75,
      group_size_preference: 85,
      conflict_navigation: 65,
      collaborative_preference: 95,
      tradition_orientation: 95,
      novelty_seeking: 10,
      stability_seeking: 95,
      meaning_orientation: 95,
      nature_connection: 75,
    }),
  },

  {
    id: 19,
    code_name: "ashkara",
    archetype_name: "TruthForger",
    archetype_essence: "Ethical action • moral clarity • integrity",
    archetype_symbol: "dual-flame",
    cultural_lineage: "Ancient Persia",
    description:
      "Truth enacted through ethical choice and action.",
    core_concepts: ["truth", "ethics", "action", "purity"],
    traits: t({
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 75,
      detail_orientation: 75,
      craftsmanship_drive: 75,
      structure_preference: 75,
      improvisation_comfort: 25,
      output_orientation: 75,
      emotional_stability: 75,
      introspection_depth: 95,
      optimism_baseline: 75,
      conflict_navigation: 60,
      influence_drive: 75,
      tradition_orientation: 75,
      novelty_seeking: 25,
      stability_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 85,
    }),
  },

  {
    id: 20,
    code_name: "alethir",
    archetype_name: "Seeker",
    archetype_essence: "Inquiry • reason • pursuit of truth",
    archetype_symbol: "open-eye",
    cultural_lineage: "Ancient Greece",
    description:
      "Truth emerges through inquiry, dialogue, and excellence.",
    core_concepts: ["inquiry", "reason", "truth", "excellence"],
    traits: t({
      abstract_thinking: 95,
      sensory_appreciation: 75,
      pattern_recognition: 95,
      detail_orientation: 75,
      craftsmanship_drive: 75,
      output_orientation: 75,
      emotional_expressiveness: 75,
      introspection_depth: 95,
      social_energy: 75,
      conflict_navigation: 70,
      influence_drive: 75,
      tradition_orientation: 75,
      novelty_seeking: 75,
      meaning_orientation: 95,
      nature_connection: 85,
    }),
  },
];

/* =========================================================
   ACCESSORS (UNCHANGED)
========================================================= */

export function getCulturalCode(codeName: string): CulturalCode | undefined {
  return CULTURAL_CODES.find((c) => c.code_name === codeName);
}

export function getAllCulturalCodes(): CulturalCode[] {
  return CULTURAL_CODES;
}

export function getAllCodeNames(): string[] {
  return CULTURAL_CODES.map((c) => c.code_name);
}
